language: go
sudo: required
dist: xenial

go:
  - 1.13.x

env:
  - GOPROXY=https://proxy.golang.org
  - GOSUMDB=https://sum.golang.org

os:
  - linux-ppc64le

go_import_path: github.com/kubernetes-sigs/cri-tools

before_install:
  - |
    (
      set -Eeuo pipefail
    )

jobs:
  include:
    - stage: Build
      os: linux-ppc64le
      script:
        -  make release

stages:
  - Build
