name: CI
on: [push, pull_request]

jobs:
  #
  # build, unit, integration, and CRI tests
  #
  linux-build-and-test:
    name: Build, Unit, Integration, and CRI (linux amd64)
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.11'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"

      - name: Checkout cri repo
        uses: actions/checkout@v2
        with:
          repository: containerd/cri
          path: src/github.com/containerd/cri
          fetch-depth: 150

      - name: Before install
        run: |
          sudo sysctl net.ipv6.conf.all.disable_ipv6=0

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            btrfs-tools \
            libseccomp2 \
            libseccomp-dev
          sudo env CRITOOL_VERSION=${{ github.sha }}
          sudo make install.deps
        working-directory:  ${{ github.workspace }}/src/github.com/containerd/cri

      - name: Install containerd
        run: |
          sudo make containerd
          sudo env PATH=$PATH GOPATH=$GOPATH make install-containerd
        working-directory:  ${{ github.workspace }}/src/github.com/containerd/cri

      - name: CRI Test
        run: |
          sudo make test-cri
        working-directory:  ${{ github.workspace }}/src/github.com/containerd/cri

      - name: Upload CRI Test log file
        uses: actions/upload-artifact@v1
        with:
          name: cri-test-${{github.sha}}.log
          path: /tmp/test-cri/containerd.log
