name: critest
on: [push, pull_request]

jobs:
  #
  # Run CRI tests against containerd
  #
  linux-build-and-test-containerd:
    strategy:
      matrix:
        version: [master, v1.4.0-beta.1]
    name: containerd ${{matrix.version}} / linux amd64
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.11'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"
          echo "::set-env name=CONTD_CRI_REPO_REF::master"

      - name: Checkout containerd/containerd ${{matrix.version}}
        uses: actions/checkout@v2
        if: ${{matrix.version != 'master'}}
        with:
          path: ${{ github.workspace }}/src/github.com/containerd/containerd
          repository: containerd/containerd
          ref: ${{matrix.version}}
          fetch-depth: 150

      - name: Set latest containerd cri repo ref
        shell: bash
        if: ${{matrix.version != 'master'}}
        run: |
          CONTD_CRI_REPO=$(grep containerd/cri ${{ github.workspace }}/src/github.com/containerd/containerd/vendor.conf | awk '{print $2}')
          echo "::set-env name=CONTD_CRI_REPO_REF::$CONTD_CRI_REPO"

      - name: Checkout containerd/cri ${{matrix.version}}
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/containerd/cri
          repository: containerd/cri
          ref: ${{env.CONTD_CRI_REPO_REF}}
          fetch-depth: 150

      - name: disable ipv6
        run: |
          sudo sysctl net.ipv6.conf.all.disable_ipv6=0

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            btrfs-tools \
            libseccomp2 \
            libseccomp-dev
          make install.deps
        working-directory: ${{ github.workspace }}/src/github.com/containerd/cri

      - name: Install containerd
        run: |
          make containerd
          sudo PATH=$PATH GOPATH=$GOPATH make install-containerd
        working-directory: ${{ github.workspace }}/src/github.com/containerd/cri

      - name: Checkout cri-tools for this commit
        uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}/src/github.com/kubernetes-sigs/cri-tools
          fetch-depth: 150

      - name: Build cri-tools
        run: |
          make
          sudo make install
        working-directory: ${{ github.workspace }}/src/github.com/kubernetes-sigs/cri-tools

      - name: Run critest
        run: |
          make test-cri
        working-directory: ${{ github.workspace }}/src/github.com/containerd/cri

      - name: Upload containerd ${{matrix.version}} logs
        uses: actions/upload-artifact@v1
        with:
          name: containerd-${{matrix.version}}-${{github.sha}}.log
          path: /tmp/test-cri/containerd.log
