name: releases
on: [push, pull_request]
jobs:
  #
  # golangci-lint
  #
  linters:
    name: Linters
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-18.04]  # TODO: pass linters on 'macos-10.15' 'windows-2019'

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.11'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/kubernetes-sigs/cri-tools

      - name: Make check
        shell: bash
        run: |
          make lint
          hack/verify-go-modules.sh
        working-directory: src/github.com/kubernetes-sigs/cri-tools

  releases:
    name: releases
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-18.04]  # TODO: make releases on 'macos-10.15' 'linux-ppc64le' 'windows-2019'
                                         # Ref: https://github.com/uraimo/run-on-arch-action

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.11'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/kubernetes-sigs/cri-tools
          fetch-depth: 0

      - name: Make release
        shell: bash
        run: make release
        working-directory: src/github.com/kubernetes-sigs/cri-tools
